In [7]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from subprocess import check_output
#print(check_output(["ls", "/datas"]).decode("utf8"))

#READING INPUT
training_data = pd.read_csv("train.csv")
testing_data=pd.read_csv("test.csv")

training_data.head()

training_data['author_num'] = training_data.author.map({'EAP':0, 'HPL':1, 'MWS':2})

X = training_data['text']
y = training_data['author_num']

print(y)

per=int(float(0.88)* len(X))
X_train=X[:per]
X_test=X[per:]
y_train=y[:per]
y_test=y[per:]

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB


vect = CountVectorizer(lowercase=False, token_pattern=r'\w+|\,')
X_cv=vect.fit_transform(X)
X_train_cv = vect.transform(X_train)
X_test_cv = vect.transform(X_test)

clf=MultinomialNB()
clf.fit(X_train_cv, y_train)
p=clf.score(X_test_cv, y_test)


X_test=vect.transform(testing_data["text"])



clf=MultinomialNB()
clf.fit(X_cv, y)
predicted_result=clf.predict_proba(X_test)
predicted_result.shape


result=pd.DataFrame()
result["id"]=testing_data["id"]
result["EAP"]=predicted_result[:,0]
result["HPL"]=predicted_result[:,1]
result["MWS"]=predicted_result[:,2]
result.head()

0        0
1        1
2        0
3        2
4        1
5        2
6        0
7        0
8        0
9        2
10       2
11       0
12       1
13       1
14       0
15       2
16       0
17       2
18       0
19       1
20       0
21       1
22       0
23       0
24       0
25       0
26       0
27       0
28       1
29       1
        ..
19549    2
19550    0
19551    0
19552    0
19553    0
19554    1
19555    0
19556    0
19557    0
19558    0
19559    1
19560    0
19561    1
19562    0
19563    2
19564    0
19565    0
19566    2
19567    0
19568    0
19569    2
19570    2
19571    1
19572    0
19573    2
19574    0
19575    0
19576    0
19577    0
19578    1
Name: author_num, dtype: int64

        id       EAP           HPL           MWS
0  id02310  0.000924  2.968107e-05  9.990459e-01
1  id24541  1.000000  3.262255e-07  9.234086e-09
2  id00134  0.003193  9.968065e-01  8.737549e-07
3  id27757  0.920985  7.901473e-02  4.811097e-07
4  id04081  0.953158  5.981884e-03  4.086011e-02

In [ ]:
result.to_csv("TO_SUBMIT.csv", index=False)